# n=18
# a=int(input("enter the number"))
# if a<18:
#     print("can't drive")
# else:
#     print("we can drive",a-n)


# date=int(input("enter the date"))
# month=int(input("enter the month"))
# year=int(input("enter the year"))
# if date<31 and date>=1 and month<=12 and year>1:
#     print(date+1,"/",month,"/",year)
# elif date>=31 and month>=12 and year>1:
#     print(31-30,"/",12-11,"/",year+1)



